// <auto-generated />
using DatabaseGeneration.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DatabaseGeneration.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210814134018_initital")]
    partial class initital
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("DatabaseGeneration.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "launch",
                            Currency = "50",
                            Name = "Burger"
                        },
                        new
                        {
                            Id = 2,
                            Category = "breakfast",
                            Currency = "25",
                            Name = "bread"
                        },
                        new
                        {
                            Id = 3,
                            Category = "dinner",
                            Currency = "35",
                            Name = "fish"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
